Adds variable to create new project of project_name if it does not al…
rancherlabs/harvester-equinix-terraform pull request #59
Opened 2024-03-21 16:37 UTC by jmarhee

…ready exist if metal_create_project is true.

2024-03-25 20:57 UTC, dnoland1 commented on data.tf
> +
Can you move this block to main.tf?

2024-03-25 21:01 UTC, dnoland1 commented on main.tf
> +  project_id = var.metal_create_project ? equinix_metal_project.new_project[0].id : data.equinix_metal_project.project.project_id
Can you add a block like this:
```terraform
locals {
  project_id = var.metal_create_project ? equinix_metal_project.new_project[0].id : data.equinix_metal_project.project.project_id
}
```
then use `local.project_id` in the resource blocks. I think this would reduce the complexity a bit.

2024-03-25 21:03 UTC, dnoland1 requested changes
I made a few inline comments. Can you have a look? I tested it out and worked fine. Could you also update the line on the README.md to document that a project can also be created if one does not exist?

2024-03-27 00:48 UTC, jmarhee commented
Thanks. Made the requested edits, let me know if I missed anything!

2024-03-27 02:31 UTC, dnoland1 commented on variables.tf
> +  default     = true
Since this is a new variable and previously we did not create a project, I think it will be less disruptive to set the default to false.

2024-03-27 02:32 UTC, dnoland1 requested changes
Sorry, found one thing. See inline comment.

2024-03-27 13:13 UTC, jmarhee commented on variables.tf
> +  default     = true
Good idea, will do.

2024-03-28 23:27 UTC, dnoland1 approved these changes
LGTM, tested both apply and destroy, with create_metal_project set to false and true

2024-03-28 23:28 UTC, merged