Create ghactions-ci.yml
rancherlabs/harvester-equinix-terraform pull request #65
Opened 2024-04-08 06:18 UTC by devenkulkarni

2024-04-08 06:32 UTC, devenkulkarni commented
@dnoland1 We need to add secrets to Github for env vars:

METAL_AUTH_TOKEN
TF_VAR_project_name

2024-04-08 17:57 UTC, dnoland1 commented on .github/workflows/ghactions-ci.yml
> +          terraform_version: 1.5.0
Can we bump this to the latest version of terraform (1.7.5)

2024-04-08 22:38 UTC, dnoland1 commented on .github/workflows/ghactions-ci.yml
> +        uses: actions/checkout@v2
Got a bunch of warnings for this:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
Can we try `actions/checkout@v4`?

2024-04-08 22:40 UTC, dnoland1 commented on .github/workflows/ghactions-ci.yml
> +        uses: hashicorp/setup-terraform@v1
Can we use the latest (v3)? See https://github.com/hashicorp/setup-terraform

2024-04-08 22:45 UTC, dnoland1 requested changes
Secrets have been added and a created a dummy commit to re-run the GH Actions. From what I can tell, doesn't look like the terraform commands are running:
<img width="1479" alt="image" src="https://github.com/rancherlabs/harvester-equinix-terraform/assets/468462/f239837f-ac6f-4246-9728-14e7fdc51d22">

2024-04-09 05:43 UTC, devenkulkarni commented
I have modified the ghactions-ci.yml with couple of changes, hope it works this time.

2024-04-09 10:51 UTC, devenkulkarni commented
After optimizing and modifying the ghactions-ci.yml, I see terraform commands running correctly. Please review and let me know if any further changes are required.

<img width="1722" alt="Screenshot 2024-04-09 at 4 19 56 PM" src="https://github.com/rancherlabs/harvester-equinix-terraform/assets/56200769/78d3671a-5585-4d0d-b29c-0de4ee2e4b35">

2024-04-09 19:58 UTC, dnoland1 approved these changes
Looks good, new version is much better!

Can you create a second PR to remove .drone.yml?

2024-04-09 19:58 UTC, merged